/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/7.0.70
 * Generated at: 2016-08-31 17:59:56 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp;

import javax.servlet.*;
import javax.servlet.http.*;
import javax.servlet.jsp.*;

public final class login_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent {

  private static final javax.servlet.jsp.JspFactory _jspxFactory =
          javax.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private volatile javax.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public javax.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final javax.servlet.http.HttpServletRequest request, final javax.servlet.http.HttpServletResponse response)
        throws java.io.IOException, javax.servlet.ServletException {

    final javax.servlet.jsp.PageContext pageContext;
    javax.servlet.http.HttpSession session = null;
    final javax.servlet.ServletContext application;
    final javax.servlet.ServletConfig config;
    javax.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    javax.servlet.jsp.JspWriter _jspx_out = null;
    javax.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<html>\r\n");
      out.write("<head>\r\n");
      out.write("    <title>Test</title>\r\n");
      out.write("    <link href='/css/main.css' rel='stylesheet' type='text/css'>\r\n");
      out.write("</head>\r\n");
      out.write("<body class=\"login\">\r\n");
      out.write("<div>\r\n");
      out.write("    <div class=\"login_wrapper\">\r\n");
      out.write("        <div class=\"animate form login_form\">\r\n");
      out.write("            <section class=\"login_content\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <h1>Вход</h1>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Логин\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"Пароль\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <a class=\"btn btn-default submit\" href=\"index.html\">Войти</a>\r\n");
      out.write("                        <a class=\"reset_pass\" href=\"#\">Забыли пароль?</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"separator\">\r\n");
      out.write("                        <p class=\"change_link\">Еще не зарегистрированы?\r\n");
      out.write("                            <a href=\"#signup\" class=\"to_register\"> Создать аккаунт </a>\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"clearfix\"></div>\r\n");
      out.write("                        <br>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("\r\n");
      out.write("        <div id=\"register\" class=\"animate form registration_form\">\r\n");
      out.write("            <section class=\"login_content\">\r\n");
      out.write("                <form>\r\n");
      out.write("                    <h1>Create Account</h1>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"text\" class=\"form-control\" placeholder=\"Username\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"email\" class=\"form-control\" placeholder=\"Email\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <input type=\"password\" class=\"form-control\" placeholder=\"Password\" required=\"\">\r\n");
      out.write("                    </div>\r\n");
      out.write("                    <div>\r\n");
      out.write("                        <a class=\"btn btn-default submit\" href=\"index.html\">Submit</a>\r\n");
      out.write("                    </div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"clearfix\"></div>\r\n");
      out.write("\r\n");
      out.write("                    <div class=\"separator\">\r\n");
      out.write("                        <p class=\"change_link\">Already a member ?\r\n");
      out.write("                            <a href=\"#signin\" class=\"to_register\"> Log in </a>\r\n");
      out.write("                        </p>\r\n");
      out.write("\r\n");
      out.write("                        <div class=\"clearfix\"></div>\r\n");
      out.write("                        <br>\r\n");
      out.write("\r\n");
      out.write("                        <div>\r\n");
      out.write("                            <h1><i class=\"fa fa-paw\"></i> Gentelella Alela!</h1>\r\n");
      out.write("                            <p>©2016 All Rights Reserved. Gentelella Alela! is a Bootstrap 3 template. Privacy and Terms</p>\r\n");
      out.write("                        </div>\r\n");
      out.write("                    </div>\r\n");
      out.write("                </form>\r\n");
      out.write("            </section>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</div>\r\n");
      out.write("\r\n");
      out.write("</body>\r\n");
      out.write("</html>");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof javax.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
